apiVersion: v1
kind: Secret
metadata:
  name: balkfet-secrets-prod
  namespace: balkfet-prod
data:
  mongodb-url: bW9uZ29kYjovL2JhbGtmZXQtbW9uZ29kYi1oZWFkbGVzcy5iYWxrZmV0LWluZnJhLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3Lw==
