apiVersion: apps/v1
kind: Deployment
metadata:
  name: balkfet-webui-local
  namespace: balkfet-local
  labels:
    app: balkfet-webui-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balkfet-webui-local
  template:
    metadata:
      labels:
        app: balkfet-webui-local
    spec:
      containers:
      - name: balkfet-webui
        image: balkfet-webui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: balkfet-webui-local
  namespace: balkfet-local
spec:
  selector:
    app: balkfet-webui-local
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: ClusterIP
